apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: cncfdemoregistry.azurecr.io/demoapp:1.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        ports:
        - containerPort: 4000
