apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: cncf-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demoapp
        image: cncfdemoregistry.azurecr.io/demoapp:1.0
        ports:
        - containerPort: 4000
