apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: cncfdemoregistry.azurecr.io/demoapp:1.0
        ports:
        - containerPort: 4000
