apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: DemoApp 
  namespace: CncfDemo
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 50% 
      maxSurge: 50% 
  selector: 
    matchLabels: 
      app: demo 
  template: 
    metadata: 
      labels: 
        app: demo 
    spec: 
      containers: 
        - name: DemoApp 
          image: cncfdemoregistry.azurecr.io/demoapp:1.0
          ports: 
            - containerPort: 8001 
          resources: 
            requests: 
              cpu: 250m 
              memory: 512Mi 
            limits: 
              memory: 2048Mi 
              cpu: 500m